# Generated by Django 3.1.7 on 2021-07-10 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210703_0052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_suscripcion', models.IntegerField()),
                ('suscrito', models.IntegerField()),
            ],
        ),
    ]
